### ISSUE TITLE
Add Support Grandpa Demon & Demons In Between 

### ISSUE THREAD

**Issue by MrKareem1980** [user95401/GemetryTrash#3]
![Screenshot_20240808-224805](https://github.com/user-attachments/assets/78fd59a4-0284-4bc1-bade-cfba74395b03)
![Screenshot_20240808-224808](https://github.com/user-attachments/assets/2e4058a4-e97f-4cb1-9519-6eff450157f5)

**Comment by user95401** [comment]
bruh no
