### ISSUE TITLE
Can you edit link?

### ISSUE THREAD

**Issue by MrKareem1980** [user95401/GemetryTrash#7]
![Screenshot_20240810-175619](https://github.com/user-attachments/assets/53af00da-d608-4f6e-9b87-d56f8aaa1ad2)
![Screenshot_20240810-175647](https://github.com/user-attachments/assets/420bf806-2b45-463d-8cdf-9dec5dbec346)
when i try to gemetrytrash it saying this is pc only

**Comment by user95401** [comment]
oh xd

**Comment by user95401** [comment]
updated

**Comment by MrKareem1980** [comment]
@user95401 are you sure?
![Screenshot_20240810-211645](https://github.com/user-attachments/assets/ff4e9a7f-8ca3-4585-96e7-ad5ed80e5b54)
i still see this

**Comment by user95401** [comment]
yea
![image](https://github.com/user-attachments/assets/a24b08b9-6a7a-41d8-ac5c-d97f5bd85e8d)
![image](https://github.com/user-attachments/assets/48aa77b3-2396-41fd-b630-44d0f6515456)

**Comment by MrKareem1980** [comment]
Thanks
